import { Restaurant } from '../types/food.types';

export const RESTAURANTS: Restaurant[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // AMERICAN
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'r1',
    name: 'Burger House',
    cuisine: 'American',
    rating: 4.5,
    deliveryTimeMin: 25,
    deliveryFee: 4.99,
    imageUri: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    categories: [
      { id: 'c1', name: 'Burgers' },
      { id: 'c2', name: 'Sides' },
      { id: 'c3', name: 'Drinks' },
    ],
    menuItems: [
      {
        id: 'm1', restaurantId: 'r1', categoryId: 'c1',
        name: 'Classic Cheeseburger',
        description: 'Juicy beef patty with cheddar, lettuce, tomato & pickles',
        price: 9.99,
        imageUri: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300',
        isAvailable: true,
      },
      {
        id: 'm2', restaurantId: 'r1', categoryId: 'c1',
        name: 'Bacon BBQ Burger',
        description: 'Double patty, crispy bacon, BBQ sauce, onion rings',
        price: 13.49,
        imageUri: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=300',
        isAvailable: true,
      },
      {
        id: 'm3', restaurantId: 'r1', categoryId: 'c1',
        name: 'Veggie Burger',
        description: 'Black bean patty with avocado, sprouts & chipotle mayo',
        price: 10.99,
        imageUri: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=300',
        isAvailable: true,
      },
      {
        id: 'm4', restaurantId: 'r1', categoryId: 'c2',
        name: 'Loaded Fries',
        description: 'Crispy fries topped with cheese sauce, jalapeños & sour cream',
        price: 5.49,
        imageUri: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=300',
        isAvailable: true,
      },
      {
        id: 'm5', restaurantId: 'r1', categoryId: 'c2',
        name: 'Onion Rings',
        description: 'Golden crispy onion rings with dipping sauce',
        price: 4.49,
        imageUri: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=300',
        isAvailable: true,
      },
      {
        id: 'm6', restaurantId: 'r1', categoryId: 'c3',
        name: 'Milkshake',
        description: 'Thick and creamy shake — chocolate, vanilla or strawberry',
        price: 4.99,
        imageUri: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r9',
    name: 'IHOP',
    cuisine: 'American',
    rating: 4.2,
    deliveryTimeMin: 20,
    deliveryFee: 6.99,
    imageUri: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=400',
    categories: [
      { id: 'c25', name: 'Pancakes' },
      { id: 'c26', name: 'Omelettes' },
      { id: 'c27', name: 'Drinks' },
    ],
    menuItems: [
      {
        id: 'm45', restaurantId: 'r9', categoryId: 'c25',
        name: 'Buttermilk Pancakes',
        description: 'Fluffy stack of three classic buttermilk pancakes',
        price: 9.99,
        imageUri: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=300',
        isAvailable: true,
      },
      {
        id: 'm46', restaurantId: 'r9', categoryId: 'c25',
        name: 'Blueberry Pancakes',
        description: 'Buttermilk pancakes bursting with fresh blueberries',
        price: 11.49,
        imageUri: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=300',
        isAvailable: true,
      },
      {
        id: 'm47', restaurantId: 'r9', categoryId: 'c26',
        name: 'Denver Omelette',
        description: 'Ham, green peppers, onion and cheddar cheese omelette',
        price: 12.99,
        imageUri: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=300',
        isAvailable: true,
      },
      {
        id: 'm48', restaurantId: 'r9', categoryId: 'c26',
        name: 'Veggie Omelette',
        description: 'Seasonal vegetables, spinach, mushrooms & Swiss cheese',
        price: 11.49,
        imageUri: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=300',
        isAvailable: true,
      },
      {
        id: 'm49', restaurantId: 'r9', categoryId: 'c27',
        name: 'Fresh Orange Juice',
        description: 'Freshly squeezed orange juice, served cold',
        price: 3.99,
        imageUri: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r10',
    name: 'Jack in the Box',
    cuisine: 'American',
    rating: 4.0,
    deliveryTimeMin: 15,
    deliveryFee: 0.99,
    imageUri: 'https://images.unsplash.com/photo-1550317138-10000687a72b?w=400',
    categories: [
      { id: 'c28', name: 'Burgers' },
      { id: 'c29', name: 'Tacos' },
      { id: 'c30', name: 'Combos' },
    ],
    menuItems: [
      {
        id: 'm50', restaurantId: 'r10', categoryId: 'c28',
        name: 'Ultimate Cheeseburger',
        description: 'Two beef patties, American cheese, mayo, mustard & pickles',
        price: 8.99,
        imageUri: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300',
        isAvailable: true,
      },
      {
        id: 'm51', restaurantId: 'r10', categoryId: 'c28',
        name: 'Bacon Ultimate',
        description: 'Double beef, crispy bacon, Swiss & American cheese',
        price: 10.49,
        imageUri: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=300',
        isAvailable: true,
      },
      {
        id: 'm52', restaurantId: 'r10', categoryId: 'c29',
        name: 'Crispy Tacos (3 pc)',
        description: 'Seasoned beef, shredded cheese & taco sauce in a crispy shell',
        price: 4.99,
        imageUri: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=300',
        isAvailable: true,
      },
      {
        id: 'm53', restaurantId: 'r10', categoryId: 'c30',
        name: 'Loaded Nachos',
        description: 'Tortilla chips, seasoned beef, cheese sauce & jalapeños',
        price: 7.99,
        imageUri: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=300',
        isAvailable: true,
      },
      {
        id: 'm54', restaurantId: 'r10', categoryId: 'c30',
        name: 'Curly Fries',
        description: 'Seasoned curly fries, perfectly crispy',
        price: 3.49,
        imageUri: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r11',
    name: "McDonald's",
    cuisine: 'American',
    rating: 4.1,
    deliveryTimeMin: 15,
    deliveryFee: 0.99,
    imageUri: 'https://images.unsplash.com/photo-1619454016518-697bc231e7cb?w=400',
    categories: [
      { id: 'c31', name: 'Burgers' },
      { id: 'c32', name: 'Chicken' },
      { id: 'c33', name: 'Sides' },
    ],
    menuItems: [
      {
        id: 'm55', restaurantId: 'r11', categoryId: 'c31',
        name: 'Big Mac',
        description: 'Two beef patties, special sauce, lettuce, cheese, pickles & onions',
        price: 6.49,
        imageUri: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300',
        isAvailable: true,
      },
      {
        id: 'm56', restaurantId: 'r11', categoryId: 'c31',
        name: 'Quarter Pounder with Cheese',
        description: 'Quarter-pound beef patty, two slices of American cheese',
        price: 7.49,
        imageUri: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=300',
        isAvailable: true,
      },
      {
        id: 'm57', restaurantId: 'r11', categoryId: 'c32',
        name: 'McChicken',
        description: 'Crispy chicken fillet with mayo & shredded lettuce',
        price: 5.49,
        imageUri: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=300',
        isAvailable: true,
      },
      {
        id: 'm58', restaurantId: 'r11', categoryId: 'c32',
        name: 'McNuggets (10 pc)',
        description: 'Tender chicken nuggets with your choice of dipping sauce',
        price: 7.99,
        imageUri: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=300',
        isAvailable: true,
      },
      {
        id: 'm59', restaurantId: 'r11', categoryId: 'c33',
        name: 'French Fries (Large)',
        description: 'World-famous golden fries, hot & crispy',
        price: 3.49,
        imageUri: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r12',
    name: 'Subway',
    cuisine: 'American',
    rating: 4.0,
    deliveryTimeMin: 15,
    deliveryFee: 1.49,
    imageUri: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=400',
    categories: [
      { id: 'c34', name: 'Subs' },
      { id: 'c35', name: 'Wraps' },
      { id: 'c36', name: 'Extras' },
    ],
    menuItems: [
      {
        id: 'm60', restaurantId: 'r12', categoryId: 'c34',
        name: 'Italian BMT',
        description: 'Genoa salami, pepperoni, ham, your choice of veggies & sauce',
        price: 8.99,
        imageUri: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=300',
        isAvailable: true,
      },
      {
        id: 'm61', restaurantId: 'r12', categoryId: 'c34',
        name: 'Turkey & Avocado',
        description: 'Oven-roasted turkey, creamy avocado, lettuce & tomato',
        price: 9.49,
        imageUri: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=300',
        isAvailable: true,
      },
      {
        id: 'm62', restaurantId: 'r12', categoryId: 'c34',
        name: 'Veggie Delite',
        description: 'Fresh veggies piled high on your choice of bread',
        price: 7.99,
        imageUri: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=300',
        isAvailable: true,
      },
      {
        id: 'm63', restaurantId: 'r12', categoryId: 'c35',
        name: 'Chicken Caesar Wrap',
        description: 'Grilled chicken, romaine, parmesan & Caesar dressing in a tomato wrap',
        price: 9.99,
        imageUri: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=300',
        isAvailable: true,
      },
      {
        id: 'm64', restaurantId: 'r12', categoryId: 'c36',
        name: 'Chocolate Chip Cookie',
        description: 'Freshly baked, warm chocolate chip cookie',
        price: 1.49,
        imageUri: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=300',
        isAvailable: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ITALIAN
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'r2',
    name: 'Pizza Palace',
    cuisine: 'Italian',
    rating: 4.7,
    deliveryTimeMin: 30,
    deliveryFee: 1.99,
    imageUri: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400',
    categories: [
      { id: 'c4', name: 'Pizzas' },
      { id: 'c5', name: 'Pasta' },
      { id: 'c6', name: 'Desserts' },
    ],
    menuItems: [
      {
        id: 'm7', restaurantId: 'r2', categoryId: 'c4',
        name: 'Margherita',
        description: 'San Marzano tomato, fresh mozzarella, basil, EVOO',
        price: 12.99,
        imageUri: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=300',
        isAvailable: true,
      },
      {
        id: 'm8', restaurantId: 'r2', categoryId: 'c4',
        name: 'Pepperoni Feast',
        description: 'Double pepperoni, mozzarella, tomato sauce',
        price: 15.99,
        imageUri: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=300',
        isAvailable: true,
      },
      {
        id: 'm9', restaurantId: 'r2', categoryId: 'c4',
        name: 'BBQ Chicken Pizza',
        description: 'Grilled chicken, BBQ sauce, red onion, mozzarella',
        price: 16.49,
        imageUri: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=300',
        isAvailable: true,
      },
      {
        id: 'm10', restaurantId: 'r2', categoryId: 'c5',
        name: 'Spaghetti Carbonara',
        description: 'Classic Roman pasta with pancetta, egg, pecorino & black pepper',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1588013273468-315fd88ea34c?w=300',
        isAvailable: true,
      },
      {
        id: 'm11', restaurantId: 'r2', categoryId: 'c5',
        name: 'Penne Arrabbiata',
        description: 'Penne in a spicy tomato and garlic sauce',
        price: 11.99,
        imageUri: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=300',
        isAvailable: true,
      },
      {
        id: 'm12', restaurantId: 'r2', categoryId: 'c6',
        name: 'Tiramisu',
        description: 'Espresso-soaked ladyfingers, mascarpone cream, cocoa dust',
        price: 6.99,
        imageUri: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r13',
    name: 'Bella Italia Kitchen',
    cuisine: 'Italian',
    rating: 4.6,
    deliveryTimeMin: 30,
    deliveryFee: 2.49,
    imageUri: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400',
    categories: [
      { id: 'c37', name: 'Antipasti' },
      { id: 'c38', name: 'Pizza' },
      { id: 'c39', name: 'Pasta' },
    ],
    menuItems: [
      {
        id: 'm65', restaurantId: 'r13', categoryId: 'c37',
        name: 'Bruschetta al Pomodoro',
        description: 'Toasted ciabatta, ripe tomatoes, garlic, fresh basil & EVOO',
        price: 7.99,
        imageUri: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=300',
        isAvailable: true,
      },
      {
        id: 'm66', restaurantId: 'r13', categoryId: 'c37',
        name: 'Caprese Salad',
        description: 'Buffalo mozzarella, heirloom tomatoes, basil & balsamic glaze',
        price: 8.99,
        imageUri: 'https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=300',
        isAvailable: true,
      },
      {
        id: 'm67', restaurantId: 'r13', categoryId: 'c38',
        name: 'Quattro Stagioni',
        description: 'Four seasons pizza: artichoke, ham, mushrooms, olives',
        price: 16.99,
        imageUri: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=300',
        isAvailable: true,
      },
      {
        id: 'm68', restaurantId: 'r13', categoryId: 'c39',
        name: 'Lasagne al Forno',
        description: 'Layers of pasta, beef ragù, béchamel & melted mozzarella',
        price: 15.99,
        imageUri: 'https://images.unsplash.com/photo-1619740455993-9d622fd01d6c?w=300',
        isAvailable: true,
      },
      {
        id: 'm69', restaurantId: 'r13', categoryId: 'c39',
        name: 'Pappardelle al Ragù',
        description: 'Wide ribbons of pasta in a slow-cooked Tuscan meat sauce',
        price: 14.49,
        imageUri: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r14',
    name: 'Olive Garden Express',
    cuisine: 'Italian',
    rating: 4.5,
    deliveryTimeMin: 25,
    deliveryFee: 1.99,
    imageUri: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400',
    categories: [
      { id: 'c40', name: 'Soups' },
      { id: 'c41', name: 'Pasta' },
      { id: 'c42', name: 'Mains' },
    ],
    menuItems: [
      {
        id: 'm70', restaurantId: 'r14', categoryId: 'c40',
        name: 'Zuppa Toscana',
        description: 'Spicy sausage, kale, potatoes in a creamy broth',
        price: 7.99,
        imageUri: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=300',
        isAvailable: true,
      },
      {
        id: 'm71', restaurantId: 'r14', categoryId: 'c40',
        name: 'Minestrone',
        description: 'Classic Italian vegetable soup with cannellini beans & pasta',
        price: 6.99,
        imageUri: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=300',
        isAvailable: true,
      },
      {
        id: 'm72', restaurantId: 'r14', categoryId: 'c41',
        name: 'Fettuccine Alfredo',
        description: 'Fettuccine in a rich parmesan cream sauce',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1588013273468-315fd88ea34c?w=300',
        isAvailable: true,
      },
      {
        id: 'm73', restaurantId: 'r14', categoryId: 'c42',
        name: 'Shrimp Scampi',
        description: 'Sautéed shrimp in garlic butter white wine sauce over linguine',
        price: 17.99,
        imageUri: 'https://images.unsplash.com/photo-1519984388953-d2406bc725e1?w=300',
        isAvailable: true,
      },
      {
        id: 'm74', restaurantId: 'r14', categoryId: 'c42',
        name: 'Chicken Parmigiana',
        description: 'Breaded chicken breast, marinara, melted mozzarella over spaghetti',
        price: 16.49,
        imageUri: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c7?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r15',
    name: 'Milano Trattoria',
    cuisine: 'Italian',
    rating: 4.7,
    deliveryTimeMin: 35,
    deliveryFee: 2.99,
    imageUri: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=400',
    categories: [
      { id: 'c43', name: 'Antipasti' },
      { id: 'c44', name: 'Risotto' },
      { id: 'c45', name: 'Pizza' },
    ],
    menuItems: [
      {
        id: 'm75', restaurantId: 'r15', categoryId: 'c43',
        name: 'Arancini',
        description: 'Crispy fried rice balls stuffed with mozzarella & meat sauce',
        price: 8.49,
        imageUri: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=300',
        isAvailable: true,
      },
      {
        id: 'm76', restaurantId: 'r15', categoryId: 'c43',
        name: 'Prosciutto e Melone',
        description: 'Aged Parma ham draped over sweet cantaloupe melon',
        price: 9.99,
        imageUri: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=300',
        isAvailable: true,
      },
      {
        id: 'm77', restaurantId: 'r15', categoryId: 'c44',
        name: 'Mushroom Risotto',
        description: 'Arborio rice, mixed wild mushrooms, parmesan & white truffle oil',
        price: 15.99,
        imageUri: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=300',
        isAvailable: true,
      },
      {
        id: 'm78', restaurantId: 'r15', categoryId: 'c44',
        name: 'Seafood Risotto',
        description: 'Clams, shrimp & scallops in a saffron-infused Arborio risotto',
        price: 19.99,
        imageUri: 'https://images.unsplash.com/photo-1519984388953-d2406bc725e1?w=300',
        isAvailable: true,
      },
      {
        id: 'm79', restaurantId: 'r15', categoryId: 'c45',
        name: 'Diavola Pizza',
        description: "Spicy 'nduja, pepperoni, chilli flakes, tomato & fior di latte",
        price: 17.49,
        imageUri: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r16',
    name: 'La Pasta House',
    cuisine: 'Italian',
    rating: 4.4,
    deliveryTimeMin: 25,
    deliveryFee: 1.49,
    imageUri: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
    categories: [
      { id: 'c46', name: 'Pasta' },
      { id: 'c47', name: 'Mains' },
      { id: 'c48', name: 'Desserts' },
    ],
    menuItems: [
      {
        id: 'm80', restaurantId: 'r16', categoryId: 'c46',
        name: 'Cacio e Pepe',
        description: 'Tonnarelli pasta, Pecorino Romano, toasted black pepper',
        price: 13.49,
        imageUri: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=300',
        isAvailable: true,
      },
      {
        id: 'm81', restaurantId: 'r16', categoryId: 'c46',
        name: 'Pasta Primavera',
        description: 'Penne with seasonal vegetables, cherry tomatoes & pesto',
        price: 12.99,
        imageUri: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=300',
        isAvailable: true,
      },
      {
        id: 'm82', restaurantId: 'r16', categoryId: 'c47',
        name: 'Osso Buco',
        description: 'Braised veal shank with gremolata, served with saffron risotto',
        price: 22.99,
        imageUri: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=300',
        isAvailable: true,
      },
      {
        id: 'm83', restaurantId: 'r16', categoryId: 'c47',
        name: 'Saltimbocca alla Romana',
        description: 'Veal escalopes, prosciutto, sage in a white wine butter sauce',
        price: 19.99,
        imageUri: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c7?w=300',
        isAvailable: true,
      },
      {
        id: 'm84', restaurantId: 'r16', categoryId: 'c48',
        name: 'Panna Cotta',
        description: 'Silky vanilla panna cotta with a fresh berry coulis',
        price: 6.49,
        imageUri: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=300',
        isAvailable: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // INDIAN
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'r5',
    name: 'Paradise',
    cuisine: 'Indian',
    rating: 4.8,
    deliveryTimeMin: 35,
    deliveryFee: 2.99,
    imageUri: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    categories: [
      { id: 'c13', name: 'Biryani' },
      { id: 'c14', name: 'Curries' },
      { id: 'c15', name: 'Starters' },
    ],
    menuItems: [
      {
        id: 'm25', restaurantId: 'r5', categoryId: 'c13',
        name: 'Hyderabadi Dum Biryani',
        description: 'Slow-cooked basmati rice with spiced mutton & caramelised onions',
        price: 14.99,
        imageUri: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=300',
        isAvailable: true,
      },
      {
        id: 'm26', restaurantId: 'r5', categoryId: 'c13',
        name: 'Chicken Biryani',
        description: 'Fragrant basmati with tender chicken, saffron & fried onions',
        price: 12.99,
        imageUri: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=300',
        isAvailable: true,
      },
      {
        id: 'm27', restaurantId: 'r5', categoryId: 'c14',
        name: 'Chicken Tikka Masala',
        description: 'Grilled chicken tikka in a rich creamy tomato-based sauce',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=300',
        isAvailable: true,
      },
      {
        id: 'm28', restaurantId: 'r5', categoryId: 'c14',
        name: 'Dal Makhani',
        description: 'Slow-cooked black lentils in a buttery tomato cream sauce',
        price: 11.99,
        imageUri: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=300',
        isAvailable: true,
      },
      {
        id: 'm29', restaurantId: 'r5', categoryId: 'c15',
        name: 'Chicken Samosa (3 pc)',
        description: 'Crispy pastry parcels filled with spiced chicken & peas',
        price: 5.99,
        imageUri: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r6',
    name: 'Astoria',
    cuisine: 'Indian',
    rating: 4.5,
    deliveryTimeMin: 30,
    deliveryFee: 2.49,
    imageUri: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400',
    categories: [
      { id: 'c16', name: 'Tandoor' },
      { id: 'c17', name: 'Curries' },
      { id: 'c18', name: 'Breads' },
    ],
    menuItems: [
      {
        id: 'm30', restaurantId: 'r6', categoryId: 'c16',
        name: 'Chicken Tandoori (Half)',
        description: 'Chicken marinated in yoghurt & spices, roasted in a clay tandoor',
        price: 15.99,
        imageUri: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300',
        isAvailable: true,
      },
      {
        id: 'm31', restaurantId: 'r6', categoryId: 'c16',
        name: 'Paneer Tikka',
        description: 'Cottage cheese cubes marinated in spiced yoghurt, chargrilled',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300',
        isAvailable: true,
      },
      {
        id: 'm32', restaurantId: 'r6', categoryId: 'c17',
        name: 'Butter Chicken',
        description: 'Tender chicken in a velvety tomato-butter-cream sauce',
        price: 14.49,
        imageUri: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=300',
        isAvailable: true,
      },
      {
        id: 'm33', restaurantId: 'r6', categoryId: 'c18',
        name: 'Garlic Naan',
        description: 'Soft leavened bread brushed with garlic butter, baked in tandoor',
        price: 3.49,
        imageUri: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=300',
        isAvailable: true,
      },
      {
        id: 'm34', restaurantId: 'r6', categoryId: 'c18',
        name: 'Aloo Paratha',
        description: 'Whole-wheat flatbread stuffed with spiced mashed potato',
        price: 4.49,
        imageUri: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r7',
    name: 'Bawarchi',
    cuisine: 'Indian',
    rating: 4.6,
    deliveryTimeMin: 25,
    deliveryFee: 1.99,
    imageUri: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400',
    categories: [
      { id: 'c19', name: 'Kebabs' },
      { id: 'c20', name: 'Rice' },
      { id: 'c21', name: 'Sweets' },
    ],
    menuItems: [
      {
        id: 'm35', restaurantId: 'r7', categoryId: 'c19',
        name: 'Seekh Kebab (4 pc)',
        description: 'Minced lamb & herb skewers cooked over charcoal',
        price: 12.99,
        imageUri: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300',
        isAvailable: true,
      },
      {
        id: 'm36', restaurantId: 'r7', categoryId: 'c19',
        name: 'Chicken Reshmi Kebab',
        description: 'Silky smooth chicken kebab in cream & cashew marinade',
        price: 13.49,
        imageUri: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300',
        isAvailable: true,
      },
      {
        id: 'm37', restaurantId: 'r7', categoryId: 'c20',
        name: 'Veg Pulao',
        description: 'Aromatic basmati rice cooked with seasonal vegetables & whole spices',
        price: 10.99,
        imageUri: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=300',
        isAvailable: true,
      },
      {
        id: 'm38', restaurantId: 'r7', categoryId: 'c21',
        name: 'Gulab Jamun (4 pc)',
        description: 'Soft milk-solid dumplings soaked in rose-flavoured sugar syrup',
        price: 4.99,
        imageUri: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=300',
        isAvailable: true,
      },
      {
        id: 'm39', restaurantId: 'r7', categoryId: 'c21',
        name: 'Kheer',
        description: 'Creamy rice pudding with cardamom, saffron & topped with pistachios',
        price: 4.49,
        imageUri: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r8',
    name: 'Mehfil',
    cuisine: 'Indian',
    rating: 4.4,
    deliveryTimeMin: 40,
    deliveryFee: 3.49,
    imageUri: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
    categories: [
      { id: 'c22', name: 'Mughlai' },
      { id: 'c23', name: 'Biryani' },
      { id: 'c24', name: 'Desserts' },
    ],
    menuItems: [
      {
        id: 'm40', restaurantId: 'r8', categoryId: 'c22',
        name: 'Nihari',
        description: 'Slow-braised lamb shank in a deeply spiced bone-marrow gravy',
        price: 15.99,
        imageUri: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=300',
        isAvailable: true,
      },
      {
        id: 'm41', restaurantId: 'r8', categoryId: 'c22',
        name: 'Haleem',
        description: 'Slow-cooked wheat, lentil & meat porridge with crispy garnish',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=300',
        isAvailable: true,
      },
      {
        id: 'm42', restaurantId: 'r8', categoryId: 'c23',
        name: 'Mutton Biryani',
        description: 'Dum-cooked mutton pieces layered with fragrant basmati rice',
        price: 16.99,
        imageUri: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=300',
        isAvailable: true,
      },
      {
        id: 'm43', restaurantId: 'r8', categoryId: 'c24',
        name: 'Shahi Tukda',
        description: 'Fried bread soaked in saffron milk, topped with rabri & nuts',
        price: 5.99,
        imageUri: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=300',
        isAvailable: true,
      },
      {
        id: 'm44', restaurantId: 'r8', categoryId: 'c24',
        name: 'Rabri Faluda',
        description: 'Rose-flavoured milk with vermicelli, basil seeds & ice cream',
        price: 5.49,
        imageUri: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=300',
        isAvailable: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // JAPANESE  (original)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'r3',
    name: 'Sushi Zen',
    cuisine: 'Japanese',
    rating: 4.8,
    deliveryTimeMin: 35,
    deliveryFee: 3.49,
    imageUri: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400',
    categories: [
      { id: 'c7', name: 'Rolls' },
      { id: 'c8', name: 'Sashimi' },
      { id: 'c9', name: 'Extras' },
    ],
    menuItems: [
      {
        id: 'm13', restaurantId: 'r3', categoryId: 'c7',
        name: 'California Roll (8 pc)',
        description: 'Crab, avocado, cucumber, sesame seeds',
        price: 10.99,
        imageUri: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=300',
        isAvailable: true,
      },
      {
        id: 'm14', restaurantId: 'r3', categoryId: 'c7',
        name: 'Spicy Tuna Roll (8 pc)',
        description: 'Fresh tuna, spicy mayo, cucumber, scallion',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1562802378-063ec186a863?w=300',
        isAvailable: true,
      },
      {
        id: 'm15', restaurantId: 'r3', categoryId: 'c7',
        name: 'Dragon Roll (8 pc)',
        description: 'Shrimp tempura inside, avocado on top, eel sauce',
        price: 15.99,
        imageUri: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=300',
        isAvailable: true,
      },
      {
        id: 'm16', restaurantId: 'r3', categoryId: 'c8',
        name: 'Salmon Sashimi (6 pc)',
        description: 'Premium Atlantic salmon, thinly sliced',
        price: 14.99,
        imageUri: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=300',
        isAvailable: true,
      },
      {
        id: 'm17', restaurantId: 'r3', categoryId: 'c9',
        name: 'Miso Soup',
        description: 'Traditional dashi broth with tofu, wakame & scallion',
        price: 3.49,
        imageUri: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=300',
        isAvailable: true,
      },
      {
        id: 'm18', restaurantId: 'r3', categoryId: 'c9',
        name: 'Edamame',
        description: 'Steamed salted soybean pods',
        price: 4.49,
        imageUri: 'https://images.unsplash.com/photo-1543352634-99a5d50ae78e?w=300',
        isAvailable: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // MEXICAN  (original)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'r4',
    name: 'Taco Fiesta',
    cuisine: 'Mexican',
    rating: 4.3,
    deliveryTimeMin: 20,
    deliveryFee: 1.49,
    imageUri: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=400',
    categories: [
      { id: 'c10', name: 'Tacos' },
      { id: 'c11', name: 'Burritos' },
      { id: 'c12', name: 'Sides' },
    ],
    menuItems: [
      {
        id: 'm19', restaurantId: 'r4', categoryId: 'c10',
        name: 'Carne Asada Taco',
        description: 'Grilled beef, cilantro, onion, salsa verde on corn tortilla',
        price: 4.49,
        imageUri: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=300',
        isAvailable: true,
      },
      {
        id: 'm20', restaurantId: 'r4', categoryId: 'c10',
        name: 'Chicken Taco',
        description: 'Marinated chicken, pickled red onion, avocado crema',
        price: 4.99,
        imageUri: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=300',
        isAvailable: true,
      },
      {
        id: 'm21', restaurantId: 'r4', categoryId: 'c11',
        name: 'Beef Burrito',
        description: 'Seasoned beef, rice, beans, cheese, sour cream, salsa',
        price: 11.99,
        imageUri: 'https://images.unsplash.com/photo-1566740933430-b5e70b06d2d5?w=300',
        isAvailable: true,
      },
      {
        id: 'm22', restaurantId: 'r4', categoryId: 'c11',
        name: 'Veggie Burrito',
        description: 'Roasted veg, guacamole, black beans, rice, pico de gallo',
        price: 10.49,
        imageUri: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=300',
        isAvailable: true,
      },
      {
        id: 'm23', restaurantId: 'r4', categoryId: 'c12',
        name: 'Guacamole & Chips',
        description: 'Fresh guacamole with house-made tortilla chips',
        price: 5.99,
        imageUri: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=300',
        isAvailable: true,
      },
      {
        id: 'm24', restaurantId: 'r4', categoryId: 'c12',
        name: 'Mexican Rice',
        description: 'Tomato-seasoned long-grain rice with cumin',
        price: 2.99,
        imageUri: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=300',
        isAvailable: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // CHINESE
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'r17',
    name: 'Panda Garden',
    cuisine: 'Chinese',
    rating: 4.4,
    deliveryTimeMin: 25,
    deliveryFee: 1.99,
    imageUri: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400',
    categories: [
      { id: 'c49', name: 'Dim Sum' },
      { id: 'c50', name: 'Noodles' },
      { id: 'c51', name: 'Mains' },
    ],
    menuItems: [
      {
        id: 'm85', restaurantId: 'r17', categoryId: 'c49',
        name: 'Har Gow (4 pc)',
        description: 'Steamed crystal shrimp dumplings in thin translucent skin',
        price: 7.99,
        imageUri: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
        isAvailable: true,
      },
      {
        id: 'm86', restaurantId: 'r17', categoryId: 'c49',
        name: 'Siu Mai (4 pc)',
        description: 'Open-topped pork & shrimp dumplings, topped with flying fish roe',
        price: 7.49,
        imageUri: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
        isAvailable: true,
      },
      {
        id: 'm87', restaurantId: 'r17', categoryId: 'c50',
        name: 'Beef Chow Fun',
        description: 'Stir-fried wide rice noodles with tender beef & bean sprouts',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=300',
        isAvailable: true,
      },
      {
        id: 'm88', restaurantId: 'r17', categoryId: 'c51',
        name: 'Kung Pao Chicken',
        description: 'Stir-fried chicken, peanuts, dried chilli & Sichuan pepper',
        price: 14.49,
        imageUri: 'https://images.unsplash.com/photo-1512003867696-6d5ce6835040?w=300',
        isAvailable: true,
      },
      {
        id: 'm89', restaurantId: 'r17', categoryId: 'c51',
        name: 'Mapo Tofu',
        description: 'Silken tofu in a spicy Sichuan bean-paste & minced pork sauce',
        price: 12.99,
        imageUri: 'https://images.unsplash.com/photo-1512003867696-6d5ce6835040?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r18',
    name: 'Dragon Wok',
    cuisine: 'Chinese',
    rating: 4.3,
    deliveryTimeMin: 20,
    deliveryFee: 1.49,
    imageUri: 'https://images.unsplash.com/photo-1512003867696-6d5ce6835040?w=400',
    categories: [
      { id: 'c52', name: 'Stir Fry' },
      { id: 'c53', name: 'Soups' },
      { id: 'c54', name: 'Rice' },
    ],
    menuItems: [
      {
        id: 'm90', restaurantId: 'r18', categoryId: 'c52',
        name: 'Sweet & Sour Pork',
        description: 'Crispy pork in a tangy pineapple sweet & sour sauce',
        price: 13.49,
        imageUri: 'https://images.unsplash.com/photo-1512003867696-6d5ce6835040?w=300',
        isAvailable: true,
      },
      {
        id: 'm91', restaurantId: 'r18', categoryId: 'c52',
        name: 'Beef & Broccoli',
        description: 'Tender beef strips & broccoli in a savoury oyster sauce glaze',
        price: 14.49,
        imageUri: 'https://images.unsplash.com/photo-1512003867696-6d5ce6835040?w=300',
        isAvailable: true,
      },
      {
        id: 'm92', restaurantId: 'r18', categoryId: 'c53',
        name: 'Hot & Sour Soup',
        description: 'Silken tofu, mushrooms, bamboo shoots in a tangy vinegar broth',
        price: 5.99,
        imageUri: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=300',
        isAvailable: true,
      },
      {
        id: 'm93', restaurantId: 'r18', categoryId: 'c53',
        name: 'Wonton Soup',
        description: 'Pork & shrimp wontons in a clear ginger-scallion broth',
        price: 6.99,
        imageUri: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=300',
        isAvailable: true,
      },
      {
        id: 'm94', restaurantId: 'r18', categoryId: 'c54',
        name: 'Yangzhou Fried Rice',
        description: 'Classic egg fried rice with prawns, char siu pork & vegetables',
        price: 11.99,
        imageUri: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r19',
    name: 'Phong-Lee',
    cuisine: 'Chinese',
    rating: 4.5,
    deliveryTimeMin: 30,
    deliveryFee: 2.49,
    imageUri: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400',
    categories: [
      { id: 'c55', name: 'Noodles' },
      { id: 'c56', name: 'Dumplings' },
      { id: 'c57', name: 'Sides' },
    ],
    menuItems: [
      {
        id: 'm95', restaurantId: 'r19', categoryId: 'c55',
        name: 'Dan Dan Noodles',
        description: 'Sesame-chilli noodles topped with spiced minced pork & peanuts',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=300',
        isAvailable: true,
      },
      {
        id: 'm96', restaurantId: 'r19', categoryId: 'c55',
        name: 'Beef Lo Mein',
        description: 'Soft egg noodles tossed with marinated beef & seasonal vegetables',
        price: 12.99,
        imageUri: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=300',
        isAvailable: true,
      },
      {
        id: 'm97', restaurantId: 'r19', categoryId: 'c56',
        name: 'Pan-Fried Pork Dumplings (6 pc)',
        description: 'Crispy-bottomed dumplings filled with pork & ginger',
        price: 9.99,
        imageUri: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
        isAvailable: true,
      },
      {
        id: 'm98', restaurantId: 'r19', categoryId: 'c56',
        name: 'Steamed Veggie Dumplings (6 pc)',
        description: 'Delicate steamed dumplings filled with tofu, cabbage & mushrooms',
        price: 8.99,
        imageUri: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
        isAvailable: true,
      },
      {
        id: 'm99', restaurantId: 'r19', categoryId: 'c57',
        name: 'Spring Rolls (3 pc)',
        description: 'Golden crispy rolls filled with glass noodles, pork & vegetables',
        price: 6.49,
        imageUri: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300',
        isAvailable: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // JAPANESE  (new)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'r20',
    name: 'Ramen Ichiban',
    cuisine: 'Japanese',
    rating: 4.7,
    deliveryTimeMin: 30,
    deliveryFee: 2.99,
    imageUri: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400',
    categories: [
      { id: 'c58', name: 'Ramen' },
      { id: 'c59', name: 'Sides' },
      { id: 'c60', name: 'Drinks' },
    ],
    menuItems: [
      {
        id: 'm100', restaurantId: 'r20', categoryId: 'c58',
        name: 'Tonkotsu Ramen',
        description: 'Rich pork bone broth, chashu pork, soft-boiled egg, nori & bamboo shoots',
        price: 14.99,
        imageUri: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=300',
        isAvailable: true,
      },
      {
        id: 'm101', restaurantId: 'r20', categoryId: 'c58',
        name: 'Spicy Miso Ramen',
        description: 'Fiery miso broth, corn, butter, ground pork, menma & scallion',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=300',
        isAvailable: true,
      },
      {
        id: 'm102', restaurantId: 'r20', categoryId: 'c58',
        name: 'Shoyu Ramen',
        description: 'Clear soy-based chicken broth, chicken chashu, narutomaki & scallion',
        price: 12.99,
        imageUri: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=300',
        isAvailable: true,
      },
      {
        id: 'm103', restaurantId: 'r20', categoryId: 'c59',
        name: 'Gyoza (6 pc)',
        description: 'Pan-fried pork & cabbage dumplings, crispy bottom, ponzu dipping sauce',
        price: 7.99,
        imageUri: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
        isAvailable: true,
      },
      {
        id: 'm104', restaurantId: 'r20', categoryId: 'c60',
        name: 'Calpico Soda',
        description: 'Japanese non-carbonated soft drink — original, strawberry or melon',
        price: 2.99,
        imageUri: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r21',
    name: 'Izakaya Yuki',
    cuisine: 'Japanese',
    rating: 4.6,
    deliveryTimeMin: 35,
    deliveryFee: 3.49,
    imageUri: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400',
    categories: [
      { id: 'c61', name: 'Yakitori' },
      { id: 'c62', name: 'Small Plates' },
      { id: 'c63', name: 'Mains' },
    ],
    menuItems: [
      {
        id: 'm105', restaurantId: 'r21', categoryId: 'c61',
        name: 'Chicken Yakitori (5 pc)',
        description: 'Charcoal-grilled chicken skewers glazed with sweet tare sauce & spring onion',
        price: 11.99,
        imageUri: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300',
        isAvailable: true,
      },
      {
        id: 'm106', restaurantId: 'r21', categoryId: 'c62',
        name: 'Takoyaki (8 pc)',
        description: 'Crispy octopus balls topped with bonito flakes, mayo & takoyaki sauce',
        price: 9.99,
        imageUri: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=300',
        isAvailable: true,
      },
      {
        id: 'm107', restaurantId: 'r21', categoryId: 'c62',
        name: 'Karaage Chicken',
        description: 'Japanese double-fried chicken thighs, yuzu kosho aioli & lemon wedge',
        price: 12.49,
        imageUri: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=300',
        isAvailable: true,
      },
      {
        id: 'm108', restaurantId: 'r21', categoryId: 'c63',
        name: 'Chicken Katsu Curry',
        description: 'Panko-breaded chicken cutlet over steamed rice with rich Japanese curry sauce',
        price: 14.99,
        imageUri: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=300',
        isAvailable: true,
      },
      {
        id: 'm109', restaurantId: 'r21', categoryId: 'c63',
        name: 'Matcha Mochi Ice Cream (3 pc)',
        description: 'Chewy rice cake parcels filled with premium matcha ice cream',
        price: 7.99,
        imageUri: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r22',
    name: 'Sakura Sushi House',
    cuisine: 'Japanese',
    rating: 4.9,
    deliveryTimeMin: 40,
    deliveryFee: 4.99,
    imageUri: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=400',
    categories: [
      { id: 'c64', name: 'Nigiri' },
      { id: 'c65', name: 'Rolls' },
      { id: 'c66', name: 'Bowls' },
    ],
    menuItems: [
      {
        id: 'm110', restaurantId: 'r22', categoryId: 'c64',
        name: 'Omakase Nigiri Set (8 pc)',
        description: "Chef's selection of premium seasonal nigiri — changes daily",
        price: 24.99,
        imageUri: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=300',
        isAvailable: true,
      },
      {
        id: 'm111', restaurantId: 'r22', categoryId: 'c65',
        name: 'Rainbow Roll (8 pc)',
        description: 'California roll topped with assorted sashimi & ripe avocado',
        price: 17.99,
        imageUri: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=300',
        isAvailable: true,
      },
      {
        id: 'm112', restaurantId: 'r22', categoryId: 'c65',
        name: 'Salmon Avocado Roll (8 pc)',
        description: 'Fresh Atlantic salmon, creamy avocado & cucumber, sesame seeds',
        price: 14.99,
        imageUri: 'https://images.unsplash.com/photo-1562802378-063ec186a863?w=300',
        isAvailable: true,
      },
      {
        id: 'm113', restaurantId: 'r22', categoryId: 'c66',
        name: 'Chirashi Bowl',
        description: "Chef's assorted sashimi over seasoned sushi rice with tamago & pickles",
        price: 21.99,
        imageUri: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=300',
        isAvailable: true,
      },
      {
        id: 'm114', restaurantId: 'r22', categoryId: 'c66',
        name: 'Salmon Teriyaki Bowl',
        description: 'Grilled salmon fillet glazed in teriyaki, steamed rice, edamame & sesame',
        price: 16.99,
        imageUri: 'https://images.unsplash.com/photo-1543352634-99a5d50ae78e?w=300',
        isAvailable: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // MEXICAN  (new)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'r23',
    name: 'El Rancho',
    cuisine: 'Mexican',
    rating: 4.4,
    deliveryTimeMin: 20,
    deliveryFee: 1.99,
    imageUri: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400',
    categories: [
      { id: 'c67', name: 'Tacos' },
      { id: 'c68', name: 'Quesadillas' },
      { id: 'c69', name: 'Mains' },
    ],
    menuItems: [
      {
        id: 'm115', restaurantId: 'r23', categoryId: 'c67',
        name: 'Al Pastor Tacos (3 pc)',
        description: 'Achiote-marinated pork, charred pineapple, onion & cilantro on corn tortilla',
        price: 12.99,
        imageUri: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=300',
        isAvailable: true,
      },
      {
        id: 'm116', restaurantId: 'r23', categoryId: 'c67',
        name: 'Birria Tacos (3 pc)',
        description: 'Slow-braised beef, Oaxacan cheese, consommé for dipping & fresh cilantro',
        price: 14.99,
        imageUri: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=300',
        isAvailable: true,
      },
      {
        id: 'm117', restaurantId: 'r23', categoryId: 'c68',
        name: 'Cheese Quesadilla',
        description: 'Flour tortilla, Oaxacan & cheddar blend, served with salsa & sour cream',
        price: 9.99,
        imageUri: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=300',
        isAvailable: true,
      },
      {
        id: 'm118', restaurantId: 'r23', categoryId: 'c69',
        name: 'Enchiladas Verde (3 pc)',
        description: 'Chicken enchiladas in roasted tomatillo salsa, crema & cotija cheese',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=300',
        isAvailable: true,
      },
      {
        id: 'm119', restaurantId: 'r23', categoryId: 'c69',
        name: 'Churros & Chocolate',
        description: 'Golden fried dough dusted with cinnamon sugar, warm chocolate dipping sauce',
        price: 6.99,
        imageUri: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r24',
    name: 'Casa Verde',
    cuisine: 'Mexican',
    rating: 4.5,
    deliveryTimeMin: 25,
    deliveryFee: 2.49,
    imageUri: 'https://images.unsplash.com/photo-1566740933430-b5e70b06d2d5?w=400',
    categories: [
      { id: 'c70', name: 'Starters' },
      { id: 'c71', name: 'Burritos' },
      { id: 'c72', name: 'Bowls' },
    ],
    menuItems: [
      {
        id: 'm120', restaurantId: 'r24', categoryId: 'c70',
        name: 'Elote (Street Corn)',
        description: 'Grilled corn on the cob, cotija cheese, chipotle crema & fresh lime',
        price: 5.99,
        imageUri: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=300',
        isAvailable: true,
      },
      {
        id: 'm121', restaurantId: 'r24', categoryId: 'c70',
        name: 'Chicken Tostada',
        description: 'Crispy tostada, refried beans, shredded chicken, crema & pico de gallo',
        price: 7.99,
        imageUri: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=300',
        isAvailable: true,
      },
      {
        id: 'm122', restaurantId: 'r24', categoryId: 'c71',
        name: 'California Burrito',
        description: 'Carne asada, crispy fries, cheese, guacamole & crema in a flour tortilla',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1566740933430-b5e70b06d2d5?w=300',
        isAvailable: true,
      },
      {
        id: 'm123', restaurantId: 'r24', categoryId: 'c72',
        name: 'Burrito Bowl',
        description: 'Cilantro-lime rice, black beans, your choice of protein & all the toppings',
        price: 12.49,
        imageUri: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=300',
        isAvailable: true,
      },
      {
        id: 'm124', restaurantId: 'r24', categoryId: 'c72',
        name: 'Tres Leches Cake',
        description: 'Fluffy sponge soaked in three milks, whipped cream & fresh berries',
        price: 6.99,
        imageUri: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r25',
    name: 'Taqueria Bonita',
    cuisine: 'Mexican',
    rating: 4.3,
    deliveryTimeMin: 15,
    deliveryFee: 0.99,
    imageUri: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=400',
    categories: [
      { id: 'c73', name: 'Tacos' },
      { id: 'c74', name: 'Nachos' },
      { id: 'c75', name: 'Drinks' },
    ],
    menuItems: [
      {
        id: 'm125', restaurantId: 'r25', categoryId: 'c73',
        name: 'Fish Tacos (3 pc)',
        description: 'Beer-battered tilapia, shredded cabbage slaw, chipotle aioli & lime',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=300',
        isAvailable: true,
      },
      {
        id: 'm126', restaurantId: 'r25', categoryId: 'c73',
        name: 'Carnitas Tacos (3 pc)',
        description: 'Slow-cooked pulled pork, diced white onion, fresh cilantro, salsa roja',
        price: 11.99,
        imageUri: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=300',
        isAvailable: true,
      },
      {
        id: 'm127', restaurantId: 'r25', categoryId: 'c74',
        name: 'Loaded Nachos Supreme',
        description: 'Tortilla chips, three-cheese blend, jalapeños, black beans, guacamole & sour cream',
        price: 13.49,
        imageUri: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=300',
        isAvailable: true,
      },
      {
        id: 'm128', restaurantId: 'r25', categoryId: 'c75',
        name: 'Michelada',
        description: 'Spicy tomato-beer cocktail with lime juice, Tajín rim & hot sauce',
        price: 6.99,
        imageUri: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=300',
        isAvailable: true,
      },
      {
        id: 'm129', restaurantId: 'r25', categoryId: 'c75',
        name: 'Horchata',
        description: 'Creamy, lightly sweet cinnamon rice milk, served ice cold',
        price: 3.99,
        imageUri: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=300',
        isAvailable: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // INDIAN  (new)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'r26',
    name: 'Spice Route',
    cuisine: 'Indian',
    rating: 4.6,
    deliveryTimeMin: 30,
    deliveryFee: 2.49,
    imageUri: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400',
    categories: [
      { id: 'c76', name: 'Dosa' },
      { id: 'c77', name: 'Curries' },
      { id: 'c78', name: 'Rice & More' },
    ],
    menuItems: [
      {
        id: 'm130', restaurantId: 'r26', categoryId: 'c76',
        name: 'Masala Dosa',
        description: 'Crispy rice-lentil crepe filled with spiced potato & onion, served with sambar & chutneys',
        price: 10.99,
        imageUri: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=300',
        isAvailable: true,
      },
      {
        id: 'm131', restaurantId: 'r26', categoryId: 'c76',
        name: 'Idli Sambar (3 pc)',
        description: 'Soft steamed rice cakes with lentil sambar, coconut & tomato chutneys',
        price: 8.99,
        imageUri: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=300',
        isAvailable: true,
      },
      {
        id: 'm132', restaurantId: 'r26', categoryId: 'c77',
        name: 'Chettinad Chicken Curry',
        description: 'Fiery South Indian curry with whole spices, kalpasi & coconut base',
        price: 14.99,
        imageUri: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=300',
        isAvailable: true,
      },
      {
        id: 'm133', restaurantId: 'r26', categoryId: 'c78',
        name: 'Coconut Rice',
        description: 'Steamed rice tossed with grated coconut, mustard seeds & curry leaves',
        price: 6.99,
        imageUri: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=300',
        isAvailable: true,
      },
      {
        id: 'm134', restaurantId: 'r26', categoryId: 'c78',
        name: 'Rasam',
        description: 'Tangy tamarind-pepper lentil soup with tomatoes & aromatics',
        price: 4.99,
        imageUri: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r27',
    name: 'Royal Darbar',
    cuisine: 'Indian',
    rating: 4.7,
    deliveryTimeMin: 40,
    deliveryFee: 3.99,
    imageUri: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
    categories: [
      { id: 'c79', name: 'Kebabs' },
      { id: 'c80', name: 'Mains' },
      { id: 'c81', name: 'Desserts' },
    ],
    menuItems: [
      {
        id: 'm135', restaurantId: 'r27', categoryId: 'c79',
        name: 'Galouti Kebab (4 pc)',
        description: 'Melt-in-the-mouth minced lamb patties with rare spices on warqi paratha',
        price: 15.99,
        imageUri: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300',
        isAvailable: true,
      },
      {
        id: 'm136', restaurantId: 'r27', categoryId: 'c79',
        name: 'Kakori Seekh Kebab (4 pc)',
        description: 'Delicate minced lamb skewers with cardamom, mace & charcoal smokiness',
        price: 14.99,
        imageUri: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300',
        isAvailable: true,
      },
      {
        id: 'm137', restaurantId: 'r27', categoryId: 'c80',
        name: 'Rogan Josh',
        description: 'Slow-cooked Kashmiri lamb in a deep crimson gravy with saffron & dried ginger',
        price: 16.99,
        imageUri: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=300',
        isAvailable: true,
      },
      {
        id: 'm138', restaurantId: 'r27', categoryId: 'c80',
        name: 'Palak Paneer',
        description: 'Fresh cottage cheese cubes in a velvety spiced spinach and fenugreek gravy',
        price: 13.99,
        imageUri: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=300',
        isAvailable: true,
      },
      {
        id: 'm139', restaurantId: 'r27', categoryId: 'c81',
        name: 'Kulfi Trio',
        description: 'Traditional Indian ice cream in mango, pistachio & malai flavours',
        price: 7.99,
        imageUri: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=300',
        isAvailable: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // CHINESE  (new)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'r28',
    name: 'Golden Dragon',
    cuisine: 'Chinese',
    rating: 4.5,
    deliveryTimeMin: 25,
    deliveryFee: 2.49,
    imageUri: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400',
    categories: [
      { id: 'c82', name: 'Dim Sum' },
      { id: 'c83', name: 'BBQ' },
      { id: 'c84', name: 'Noodles' },
    ],
    menuItems: [
      {
        id: 'm140', restaurantId: 'r28', categoryId: 'c82',
        name: 'BBQ Pork Bao (3 pc)',
        description: 'Fluffy steamed buns filled with sticky-sweet char siu pork',
        price: 8.49,
        imageUri: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
        isAvailable: true,
      },
      {
        id: 'm141', restaurantId: 'r28', categoryId: 'c82',
        name: 'Turnip Cake (Lo Bak Go)',
        description: 'Pan-fried radish cake with XO sauce — a dim sum classic',
        price: 7.49,
        imageUri: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
        isAvailable: true,
      },
      {
        id: 'm142', restaurantId: 'r28', categoryId: 'c83',
        name: 'Char Siu Platter',
        description: 'Honey-glazed Cantonese BBQ pork, steamed rice & seasonal greens',
        price: 16.49,
        imageUri: 'https://images.unsplash.com/photo-1512003867696-6d5ce6835040?w=300',
        isAvailable: true,
      },
      {
        id: 'm143', restaurantId: 'r28', categoryId: 'c84',
        name: 'Wonton Noodle Soup',
        description: 'Thin egg noodles, plump pork & shrimp wontons in a golden clear broth',
        price: 11.99,
        imageUri: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=300',
        isAvailable: true,
      },
      {
        id: 'm144', restaurantId: 'r28', categoryId: 'c84',
        name: 'Egg Tart (4 pc)',
        description: 'Silky baked custard in a flaky buttery pastry shell — freshly baked',
        price: 5.99,
        imageUri: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=300',
        isAvailable: true,
      },
    ],
  },
  {
    id: 'r29',
    name: 'Sichuan House',
    cuisine: 'Chinese',
    rating: 4.6,
    deliveryTimeMin: 35,
    deliveryFee: 3.49,
    imageUri: 'https://images.unsplash.com/photo-1512003867696-6d5ce6835040?w=400',
    categories: [
      { id: 'c85', name: 'Spicy Mains' },
      { id: 'c86', name: 'Hot Pot' },
      { id: 'c87', name: 'Sides' },
    ],
    menuItems: [
      {
        id: 'm145', restaurantId: 'r29', categoryId: 'c85',
        name: 'Twice-Cooked Pork',
        description: 'Sliced pork belly stir-fried with leeks, garlic shoots & spicy doubanjiang',
        price: 14.99,
        imageUri: 'https://images.unsplash.com/photo-1512003867696-6d5ce6835040?w=300',
        isAvailable: true,
      },
      {
        id: 'm146', restaurantId: 'r29', categoryId: 'c85',
        name: 'Fish Fragrant Eggplant',
        description: 'Silky eggplant braised in a Sichuan spicy bean sauce with pork & ginger',
        price: 12.99,
        imageUri: 'https://images.unsplash.com/photo-1512003867696-6d5ce6835040?w=300',
        isAvailable: true,
      },
      {
        id: 'm147', restaurantId: 'r29', categoryId: 'c86',
        name: 'Sichuan Hot Pot (for 2)',
        description: 'Numbing mala broth with an array of meats, tofu & vegetables to cook tableside',
        price: 29.99,
        imageUri: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=300',
        isAvailable: true,
      },
      {
        id: 'm148', restaurantId: 'r29', categoryId: 'c87',
        name: 'Chilli Oil Wontons (8 pc)',
        description: 'Pork & shrimp wontons drenched in house chilli oil, black vinegar & sesame',
        price: 10.99,
        imageUri: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
        isAvailable: true,
      },
      {
        id: 'm149', restaurantId: 'r29', categoryId: 'c87',
        name: 'Sesame Cold Noodles',
        description: 'Chilled wheat noodles in a toasted sesame-soy dressing with cucumber & chilli',
        price: 9.99,
        imageUri: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=300',
        isAvailable: true,
      },
    ],
  },
];

export const ALL_CUISINES = ['All', ...Array.from(new Set(RESTAURANTS.map((r) => r.cuisine)))];
